// Code generated by protoc-gen-go. DO NOT EDIT.
// source: src/golang/src/grpc-sample/proto/person.proto

package person

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type GetMessage struct {
	TargetType           int64    `protobuf:"varint,1,opt,name=target_type,json=targetType,proto3" json:"target_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetMessage) Reset()         { *m = GetMessage{} }
func (m *GetMessage) String() string { return proto.CompactTextString(m) }
func (*GetMessage) ProtoMessage()    {}
func (*GetMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_b9539cbff28ac142, []int{0}
}

func (m *GetMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMessage.Unmarshal(m, b)
}
func (m *GetMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMessage.Marshal(b, m, deterministic)
}
func (m *GetMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMessage.Merge(m, src)
}
func (m *GetMessage) XXX_Size() int {
	return xxx_messageInfo_GetMessage.Size(m)
}
func (m *GetMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMessage.DiscardUnknown(m)
}

var xxx_messageInfo_GetMessage proto.InternalMessageInfo

func (m *GetMessage) GetTargetType() int64 {
	if m != nil {
		return m.TargetType
	}
	return 0
}

type GetPersonResponse struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	CreatedDate          string   `protobuf:"bytes,3,opt,name=created_date,json=createdDate,proto3" json:"created_date,omitempty"`
	UpdatedDate          string   `protobuf:"bytes,4,opt,name=updated_date,json=updatedDate,proto3" json:"updated_date,omitempty"`
	LastAccessDate       string   `protobuf:"bytes,5,opt,name=last_access_date,json=lastAccessDate,proto3" json:"last_access_date,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPersonResponse) Reset()         { *m = GetPersonResponse{} }
func (m *GetPersonResponse) String() string { return proto.CompactTextString(m) }
func (*GetPersonResponse) ProtoMessage()    {}
func (*GetPersonResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b9539cbff28ac142, []int{1}
}

func (m *GetPersonResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPersonResponse.Unmarshal(m, b)
}
func (m *GetPersonResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPersonResponse.Marshal(b, m, deterministic)
}
func (m *GetPersonResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPersonResponse.Merge(m, src)
}
func (m *GetPersonResponse) XXX_Size() int {
	return xxx_messageInfo_GetPersonResponse.Size(m)
}
func (m *GetPersonResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPersonResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetPersonResponse proto.InternalMessageInfo

func (m *GetPersonResponse) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *GetPersonResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GetPersonResponse) GetCreatedDate() string {
	if m != nil {
		return m.CreatedDate
	}
	return ""
}

func (m *GetPersonResponse) GetUpdatedDate() string {
	if m != nil {
		return m.UpdatedDate
	}
	return ""
}

func (m *GetPersonResponse) GetLastAccessDate() string {
	if m != nil {
		return m.LastAccessDate
	}
	return ""
}

func init() {
	proto.RegisterType((*GetMessage)(nil), "GetMessage")
	proto.RegisterType((*GetPersonResponse)(nil), "GetPersonResponse")
}

func init() {
	proto.RegisterFile("src/golang/src/grpc-sample/proto/person.proto", fileDescriptor_b9539cbff28ac142)
}

var fileDescriptor_b9539cbff28ac142 = []byte{
	// 237 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x90, 0x31, 0x4b, 0xc4, 0x40,
	0x10, 0x85, 0x4d, 0xee, 0x3c, 0xb8, 0x89, 0x1c, 0xba, 0x55, 0xb0, 0xf1, 0x4c, 0x95, 0x26, 0x09,
	0x68, 0x63, 0x2b, 0x08, 0x57, 0x09, 0x12, 0xec, 0xc3, 0xb8, 0x3b, 0x84, 0x83, 0x5c, 0x76, 0xd9,
	0x19, 0x8b, 0xfb, 0x45, 0xfe, 0x4d, 0xb9, 0x49, 0x30, 0x85, 0xdd, 0xdb, 0x6f, 0x3f, 0x96, 0xf7,
	0x16, 0x2a, 0x8e, 0xb6, 0xe9, 0xfd, 0x80, 0x63, 0xdf, 0x68, 0x8c, 0xc1, 0x56, 0x8c, 0xa7, 0x30,
	0x50, 0x13, 0xa2, 0x17, 0xdf, 0x04, 0x8a, 0xec, 0xc7, 0x5a, 0x0f, 0x45, 0x05, 0x70, 0x20, 0x79,
	0x27, 0x66, 0xec, 0xc9, 0x3c, 0x40, 0x26, 0x18, 0x7b, 0x92, 0x4e, 0xce, 0x81, 0xf2, 0x64, 0x9f,
	0x94, 0xab, 0x16, 0x26, 0xf4, 0x79, 0x0e, 0x54, 0xfc, 0x24, 0x70, 0x77, 0x20, 0xf9, 0xd0, 0x27,
	0x5a, 0xe2, 0xe0, 0x47, 0x26, 0xb3, 0x83, 0xf4, 0xe8, 0x66, 0x3b, 0x3d, 0x3a, 0x63, 0x60, 0x3d,
	0xe2, 0x89, 0xf2, 0x74, 0x9f, 0x94, 0xdb, 0x56, 0xb3, 0x79, 0x84, 0x1b, 0x1b, 0x09, 0x85, 0x5c,
	0xe7, 0x50, 0x28, 0x5f, 0xe9, 0x5d, 0x36, 0xb3, 0x37, 0x14, 0x55, 0xbe, 0x83, 0x5b, 0x94, 0xf5,
	0xa4, 0xcc, 0x4c, 0x95, 0x12, 0x6e, 0x07, 0x64, 0xe9, 0xd0, 0x5a, 0x62, 0x9e, 0xb4, 0x6b, 0xd5,
	0x76, 0x17, 0xfe, 0xaa, 0xf8, 0x62, 0x3e, 0xbd, 0xc0, 0x66, 0x6a, 0x69, 0x6a, 0xd8, 0xfe, 0x55,
	0x36, 0x59, 0xbd, 0xcc, 0xbd, 0x37, 0xf5, 0xbf, 0x2d, 0xc5, 0xd5, 0xd7, 0x46, 0x7f, 0xe6, 0xf9,
	0x37, 0x00, 0x00, 0xff, 0xff, 0x10, 0x21, 0x63, 0xd4, 0x4a, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PersonClient is the client API for Person service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PersonClient interface {
	GetPerson(ctx context.Context, in *GetMessage, opts ...grpc.CallOption) (*GetPersonResponse, error)
}

type personClient struct {
	cc *grpc.ClientConn
}

func NewPersonClient(cc *grpc.ClientConn) PersonClient {
	return &personClient{cc}
}

func (c *personClient) GetPerson(ctx context.Context, in *GetMessage, opts ...grpc.CallOption) (*GetPersonResponse, error) {
	out := new(GetPersonResponse)
	err := c.cc.Invoke(ctx, "/Person/GetPerson", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PersonServer is the server API for Person service.
type PersonServer interface {
	GetPerson(context.Context, *GetMessage) (*GetPersonResponse, error)
}

func RegisterPersonServer(s *grpc.Server, srv PersonServer) {
	s.RegisterService(&_Person_serviceDesc, srv)
}

func _Person_GetPerson_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PersonServer).GetPerson(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Person/GetPerson",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PersonServer).GetPerson(ctx, req.(*GetMessage))
	}
	return interceptor(ctx, in, info, handler)
}

var _Person_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Person",
	HandlerType: (*PersonServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPerson",
			Handler:    _Person_GetPerson_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "src/golang/src/grpc-sample/proto/person.proto",
}
